'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('drinks', 
    [
      {
        str_alcoholic: "Optional alcohol",
        str_category: 1,
        str_drink: "GG",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg",
        str_glass: 1,
        str_instructions: "Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.",
        str_instructionsDE: "Den Galliano-Likör über Eis gießen. Füllen Sie den Rest des Glases mit Ginger Ale und das ist alles, was dazu gehört. Du hast jetzt ein eigenes GG.",
        str_instructionsES: null,
        str_instructionsFR: null,
        str_instructionsIT: 'Versare il liquore Galliano su ghiaccio.'
        + 'Riempi il resto del bicchiere con ginger ale e questo è tutto.'
        + 'Ora hai il tuo GG personale.',
        str_tags: null,
        str_video: null,
      },
      {
        str_alcoholic: "Alcoholic",
        str_category: 2,
        str_drink: "A1",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg",
        str_glass: 6,
        str_instructions: "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
        str_instructionsDE: "Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.",
        str_instructionsES: "Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.",
        str_instructionsFR: null,
        str_instructionsIT: "Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.",
        str_tags: null,
        str_video: null,
      },
      {
        str_alcoholic: "Alcoholic",
        str_category: 3,
        str_drink: "252",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg",
        str_glass: 2,
        str_instructions: "Add both ingredients to shot glass, shoot, and get drunk quick",
        str_instructionsDE: "Beide Zutaten in ein Schnapsglas geben.",
        str_instructionsES: null,
        str_instructionsFR: null,
        str_instructionsIT: "Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente",
        str_tags: null,
        str_video: null,
      },
      {
        str_alcoholic: "Alcoholic",
        str_category: 3,
        str_drink: "747",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg",
        str_glass: 2,
        str_instructions: "pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!",
        str_instructionsDE: "Gießen Sie kaluha, dann Baileys, dann Frangelico nicht gekühlt und nicht geschichtet -- SERVE!!!!!!!!",
        str_instructionsES: null,
        str_instructionsFR: null,
        str_instructionsIT: "Versa Kahlua, Baileys e poi Frangelico.",
        str_tags: null,
        str_video: null,
      },
      {
        str_alcoholic: "Alcoholic",
        str_category: 1,
        str_drink: "Kir",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg",
        str_glass: 3,
        str_instructions: "Add the crème de cassis to the bottom of the glass, then top up with wine.",
        str_instructionsDE: "Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.",
        str_instructionsES: null,
        str_instructionsFR: null,
        str_instructionsIT: "Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.",
        str_tags: "IBA,ContemporaryClassic",
        str_video: null,
      },
      {
        str_alcoholic: "Alcoholic",
        str_category: 3,
        str_drink: "ABC",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg",
        str_glass: 2,
        str_instructions: "Layered in a shot glass.",
        str_instructionsDE: "Schichtaufbau in einem Schnapsglas.",
        str_instructionsES: "Coloque todos los ingredientes en un vaso de chupito.",
        str_instructionsFR: null,
        str_instructionsIT: "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
        str_tags: null,
        str_video: null,
      },
      {
        str_alcoholic: "Alcoholic",
        str_category: 2,
        str_drink: "Ace",
        str_drink_thumb: "https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg",
        str_glass: 4,
        str_instructions: "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
        str_instructionsDE: "Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.",
        str_instructionsES: "Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.",
        str_instructionsFR: null,
        str_instructionsIT: "Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.",
        str_tags: null,
        str_video: null,
      },
    ], {});
      },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('drinks', null, {});
  }
};
